<!-- 1-41.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
  <!ELEMENT libro EMPTY>
  <!ATTLIST libro autor NMTOKEN #REQUIRED>
]>
 
<libro autor="Mario Vargas LLosa" />

<!-- Corregido -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
  <!ELEMENT libro EMPTY>
  <!ATTLIST libro autor NMTOKENS #REQUIRED>
]>

<!-- 2-42.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventores [
  <!ELEMENT inventores>
  <!ELEMENT inventor EMPTY>
  <!ATTLIST inventor invento CDATA #REQUIRED>
  <!ATTLIST inventor nombre ID #REQUIRED>
]>
 
<inventores>
  <inventor nombre="Robert Adler" invento="Mando a distancia" />
  <inventor nombre="Laszlo Josef Biro" invento="Bolígrafo" />
  <inventor nombre="Josephine Garis Cochran" invento="Lavaplatos" />
  <inventor invento="Fuego" />
</inventores>

<!-- Corregido -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventores [
  <!ELEMENT inventores (inventor+)>
  <!ELEMENT inventor EMPTY>
  <!ATTLIST inventor invento CDATA #REQUIRED>
  <!ATTLIST inventor nombre NMTOKENS #IMPLIED>
]>

<!-- 3-43.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cosasPorHacer [
  <!ELEMENT cosasPorHacer (cosa)>
  <!ELEMENT cosa EMPTY>
  <!ATTLIST cosa fecha CDATA #REQUIRED>
  <!ATTLIST cosa asunto CDATA #REQUIRED>
  <!ATTLIST cosa fechaLimite CDATA #REQUIRED>  
]>
 
<cosasPorHacer>
  <cosa fecha="20 de febrero de 2011" fechaLimite="1 de marzo de 2011">
  Preparar ejercicios de DTDs</cosa>
  <cosa fecha="21 de febrero de 2011" fechaLimite="5 de marzo de 2011">
  Preparar tema XSLT</cosa>
</cosasPorHacer>

<!-- Corregido -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cosasPorHacer [
  <!ELEMENT cosasPorHacer (cosa+)>
  <!ELEMENT cosa (#PCDATA)>
  <!ATTLIST cosa fecha CDATA #REQUIRED>
  <!ATTLIST cosa asunto CDATA #IMPLIED>
  <!ATTLIST cosa fechaLimite CDATA #REQUIRED>  
]>

<!-- 4-44.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resoluciones [
  <!ELEMENT resoluciones EMPTY>
  <!ATTLIST resoluciones nombre NMTOKEN #REQUIRED>
  <!ATTLIST resoluciones alto CDATA #REQUIRED>
  <!ATTLIST resoluciones ancho CDATA #REQUIRED>
]>
 
<resoluciones>
  <resolucion nombre="VGA" alto="480" ancho="640" />
  <resolucion nombre="XGA" alto="1024" ancho="768" />
  <resolucion nombre="HD 1080" alto="1920" ancho="1080" />
</resoluciones>

<!-- Corregido -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resoluciones [
  <!ELEMENT resoluciones (resolucion+)>
  <!ELEMENT resolucion EMPTY>
  <!ATTLIST resolucion nombre CDATA #REQUIRED>
  <!ATTLIST resolucion alto CDATA #REQUIRED>
  <!ATTLIST resolucion ancho CDATA #REQUIRED>
]>

<!-- 5-45.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albumesMortadelo [
  <!ELEMENT albumesMortadelo (album*)>
  <!ELEMENT album (nombre, fecha)>
  <!ATTLIST album nombre CDATA #REQUIRED>
  <!ATTLIST album fecha(1969,1970,1971,1972,1973,1974) #REQUIRED>
]>
 
<albumesMortadelo>
  <album nombre="El sulfato atómico" fecha="1969"/>
  <album nombre="La caja de diez cerrojos" fecha="1971"/>
  <album nombre="El otro yo del profesor Bacterio" fecha="1973"/>
  <album nombre="Los cacharros majaretas" fecha="1974"/>
</albumesMortadelo>

<!-- Corregido -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albumesMortadelo [
  <!ELEMENT albumesMortadelo (album*)>
  <!ELEMENT album EMPTY>
  <!ATTLIST album nombre CDATA #REQUIRED>
  <!ATTLIST album fecha (1969|1970|1971|1972|1973|1974) #REQUIRED>
]>