<!-- 1- dtd_12.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE letras [
  <!ELEMENT letras (letra)>
<!ELEMENT letra (#PCDATA)>
]>

<!-- Sin corregir -->
<letras>
    <letra>m</letra>
    <letra>uve doble</letra>
</letras <!-- corregido -->
<!-- cierre de ultimo letras -->
<letras>
    <letra>m</letra>
</letras>

<!-- 2- dtd_13.xml  -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
  <!ELEMENT colores (color*)>
<!ELEMENT color (#PCDATA)>
]>
 
<colores>
    <color>azul marino</color>
    negro
    <color>amarillo</color>
</colores>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
  <!ELEMENT colores (color*)>
<!ELEMENT color (#PCDATA)>
]>
<!--  negro sin etiqueta -->
<colores>
    <color>azul marino</color>
    <color>negro</color>
    <color>amarillo</color>
</colores>


<!-- 3- dtd_14.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flores [
  <!ELEMENT flores (flor+)>
<!ELEMENT flor (#PCDATA)>
]>
 
<flores>
</flores>

<!-- minimo una etiqueta flor -->
<flores>
    <flor>Rosa</flor>s
</flores>

<!-- 4- dtd_15.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales [
  <!ELEMENT animales (animal*)>
<!ELEMENT animal (#PCDATA)>
]>
 
<animales>
    <perro>Caniche</perro>
    <gato>Siamés</gato>
</animales>

<!-- hay que ponerle animal dentro de animales -->
<animales>
    <animal>Caniche</animal>
    <animal>Siamés</animal>
</animales>

<!-- 5- dtd_16.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escritores [
  <!ELEMENT escritores (escritor*)>
<!ELEMENT escritor (nombre, nacimiento)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
]>
 
<escritores>
    <escritor>
        <nombre>Mario Vargas LLosa</nombre>
        <nacimiento>28 de marzo de 1936</nacimiento>
    </escritor>
    <escritor>
        <nacimiento>1 de abril de 1929</nacimiento>
        <nombre>Milan Kundera</nombre>
    </escritor>
</escritores>

<!-- en el segundo escritor esta desordenado nombre nacimiento hay que respetar la orden -->

<escritores>
    <escritor>
        <nombre>Mario Vargas LLosa</nombre>
        <nacimiento>28 de marzo de 1936</nacimiento>
    </escritor>
    <escritor>
        <nombre>Milan Kundera</nombre>
        <nacimiento>1 de abril de 1929</nacimiento>
    </escritor>
</escritores>

<!-- 6- dtd_17.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
  <!ELEMENT musicos (musico*)>
<!ELEMENT musico ((nombre | apodo), fechaNacimiento)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apodo (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
]>
<musicos>
    <musico>
        <nombre>Antonio Vivaldi</nombre>
        <apodo>El cura pelirrojillo</apodo>
        <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
    </musico>
    <musico>
        <nombre>Johann Sebastian Bach</nombre>
        <apodo>El viejo peluca</apodo>
        <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
    </musico>
</musicos>

<!-- nombre o apodo hay que elegir -->
<musicos>
    <musico>
        <nombre>Antonio Vivaldi</nombre>
        <!-- <apodo>El cura pelirrojillo</apodo> -->
        <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
    </musico>
    <musico>
        <nombre>Johann Sebastian Bach</nombre>
        <!-- <apodo>El viejo peluca</apodo> -->
        <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
    </musico>
</musicos>

<!-- 7- dtd_18.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
  <!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefonoFijo (#PCDATA)>
<!ELEMENT telefonoMovil (#PCDATA)>
]>
 <agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Unión Europea)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
    </contacto>
</agenda>
<!-- -->
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
</agenda>

<!-- 8- dtd_19.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar [
  <!ELEMENT sistemaSolar (cuerpo*)>
<!ELEMENT cuerpo ((planeta|satelite|asteroide)+)>
<!ELEMENT planeta (#PCDATA)>
<!ELEMENT satelite (#PCDATA)>
<!ELEMENT asteroide (#PCDATA)>
]>

<sistemaSolar>
    <cuerpo>
        <planeta>Tierra</planeta>
        <satelite>Luna</satelite>
    </cuerpo>
    <asteroide>Ceres</asteroide>
</sistemaSolar>
<!-- Corregido: quitar asteroide y satelite-->
<sistemaSolar>
    <cuerpo>
        <planeta>Tierra</planeta>
    </cuerpo>
</sistemaSolar>