<!-- 1- 31.xml -->
<!DOCTYPE persona [
  <!ELEMENT persona EMPTY>
  <!ATTLIST persona nombre CDATA #IMPLIED>
]>
 
<persona dni="03141592E" />

<!-- Corregido -->

<persona nombre="03141592E" />
<!-- 2- 32.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula [
  <!ELEMENT pelicula EMPTY>
  <!ATTLIST pelicula titulo CDATA #IMPLIED>
]>
 
<pelicula titulo="La diligencia" genero="oeste" />

<!-- Corregido -->

<pelicula titulo="La diligencia" />

<!-- 3- 33.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuadros [
  <!ELEMENT cuadros (cuadro*)>
  <!ELEMENT cuadro EMPTY>
  <!ATTLIST cuadro titulo ID #REQUIRED>
  <!ATTLIST cuadro autor CDATA #REQUIRED>
]>
 
<cuadros>
  <cuadro titulo="Adán y Eva" autor="Alberto Durero" />
  <cuadro autor="Lucas Cranach, el viejo" titulo="Adán y Eva" />
</cuadros>

<!-- Corregido -->
<cuadros>
  <cuadro titulo="Adán y Eva" autor="Alberto Durero" />
  <cuadro autor="Lucas Cranach, el viejo" titulo="AdányEva 2:ElretornodeYisus" />
</cuadros>

<!-- 4- 34.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaCompra [
  <!ELEMENT listaCompra (item*)>
  <!ELEMENT item EMPTY>
  <!ATTLIST item nombre CDATA #REQUIRED>
  <!ATTLIST item cantidad CDATA #REQUIRED>
]>
 
<listaCompra>
  <leche cantidad="12 litros" ></leche>
  <pan cantidad="3 barras de cuarto" />
</listaCompra>

<!-- Corregido -->

<listaCompra>
  <item nombre="leche" cantidad="12 litros" />
  <item nombre="pan" cantidad="3 barras de cuarto" />
</listaCompra>

<!-- 5- 35.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
  <!ELEMENT futbol (jugador*)>
  <!ELEMENT jugador EMPTY>
  <!ATTLIST jugador nombre NMTOKENS #REQUIRED>
  <!ATTLIST jugador codigo ID #REQUIRED>
]>
 
<futbol>
  <jugador nombre="Alfredo Di Stéfano" codigo="1"/>
  <jugador nombre="Edson Arantes do Nascimento, Pelé" codigo="2" />
  <jugador nombre="Diego Armando Maradona" codigo="3" />
  <jugador nombre="Johan Cruyff" codigo="4" />
</futbol>

<!-- Corregido -->

<futbol>
  <jugador nombre="Alfredo Di Stéfano" codigo="c1"/>
  <jugador nombre="Edson Arantes do Nascimento Pelé" codigo="c2" />
  <jugador nombre="Diego Armando Maradona" codigo="c3" />
  <jugador nombre="Johan Cruyff" codigo="c4" />
</futbol>

<!-- 6- 36.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
  <!ELEMENT futbol ((jugador|equipo)*)>
  <!ELEMENT jugador EMPTY>
  <!ATTLIST jugador nombre NMTOKENS #REQUIRED>
  <!ATTLIST jugador codigo ID #REQUIRED>
  <!ELEMENT equipo EMPTY>
  <!ATTLIST equipo nombre CDATA #REQUIRED>
  <!ATTLIST equipo jugadores IDREFS #IMPLIED>
]>
 <futbol>
  <jugador nombre="Alfredo Di Stéfano" codigo="ads"/>
  <jugador nombre="Edison Arantes do Nascimento" codigo="ean" />
  <jugador nombre="Diego Armando Maradona" codigo="dam" />
  <jugador nombre="Johan Cruyff" codigo="jc" />
  <equipo nombre="Società Sportiva Calcio Napoli" jugadores="Maradona" />
  <equipo nombre="Futbol Club Barcelona" jugadores="Cruyff, Maradona" />
</futbol>

<!-- Corregido -->

 <futbol>
  <jugador nombre="Alfredo Di Stéfano" codigo="ads"/>
  <jugador nombre="Edison Arantes do Nascimento" codigo="ean" />
  <jugador nombre="Diego Armando Maradona" codigo="dam" />
  <jugador nombre="Johan Cruyff" codigo="jc" />
  <equipo nombre="Società Sportiva Calcio Napoli" jugadores="ads" />
  <equipo nombre="Futbol Club Barcelona" jugadores="jc" />
</futbol>