=== jonberge1337/alternativa-reto-8/ejercicios xsd indivisuales/tarea6/pedidos.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:simpleType name="tipoFecha">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-3][0-9])-([0-1][1-9])-([1-2][0-9]{3})" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="tipoPedido">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z]" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="tipoDescripcion">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z a-z]+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="pedidos">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pedido" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="pedido">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="fecha"/>
        <xsd:element ref="pu"/>
        <xsd:element ref="cantidad"/>
        <xsd:element ref="descripcion"/>
        <xsd:element ref="tipo"/>
      </xsd:sequence>
      <xsd:attribute type="xsd:byte" name="cod" use="optional"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="fecha" type="tipoFecha"/>
  <xsd:element name="pu" type="xsd:float"/>
  <xsd:element name="cantidad" type="xsd:byte"/>
  <xsd:element name="descripcion" type="tipoDescripcion"/>
  <xsd:element name="tipo" type="tipoPedido"/>
</xsd:schema>

=== jonberge1337/alternativa-reto-8/ejercicios xsd indivisuales/tarea6/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>

<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" si:noNamespaceSchemaLocation="pedidos.xsd">
    <pedido cod="1">
        <fecha>01-01-2013</fecha>
        <pu>45.5</pu>
        <cantidad>2</cantidad>
        <descripcion>Botella de Vino</descripcion>
        <tipo>C</tipo>
    </pedido>
    <pedido cod="2">
        <fecha>31-12-2012</fecha>
        <pu>25</pu>
        <cantidad>1</cantidad>
        <descripcion>Menu Ejecutivo</descripcion>
        <tipo>A</tipo>
    </pedido>
</pedidos>
