=== jonberge1337/alternativa-reto-8/ejercicios xsd indivisuales/tarea7/faq.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:simpleType name="tipoEmail">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[^@]+@[^\.]+\..+"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="tipoFecha">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="( [1-3][0-9]).(ENERO|FEBRERO|MAYO).([0-9]{2} )" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="tipoCaracteristica">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[ 0-9'.a-zA-ZñáéíóúÁÉÍÓÚ¿¡?!]+" />
		</xsd:restriction>
	</xsd:simpleType>
  <xsd:element name="FAQ">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="INFO"/>
        <xsd:element ref="PART"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="INFO">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="TITULO"/>
        <xsd:element ref="AUTOR"/>
        <xsd:element ref="EMAIL"/>
        <xsd:element ref="VERSION"/>
        <xsd:element ref="FECHA"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="PART">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Q" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute type="xsd:byte" name="number"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Q">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="QTEXT"/>
        <xsd:element ref="A"/>
      </xsd:sequence>
      <xsd:attribute type="xsd:byte" name="id"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="TITULO" type="tipoCaracteristica"/>
  <xsd:element name="AUTOR" type="tipoCaracteristica"/>
  <xsd:element name="EMAIL" type="xsd:string"/>
  <xsd:element name="VERSION" type="xsd:float"/>
  <xsd:element name="FECHA" type="tipoFecha"/>
  <xsd:element name="QTEXT" type="tipoCaracteristica"/>
  <xsd:element name="A" type="tipoCaracteristica"/>
</xsd:schema>

=== jonberge1337/alternativa-reto-8/ejercicios xsd indivisuales/tarea7/faq.xml
<?xml version="1.0" encoding="UTF-8"?>

<FAQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" si:noNamespaceSchemaLocation="faq.xsd">

    <INFO>

        <TITULO> WINDOWS98? SOLO SI ME OBLIGAN! </TITULO>

        <AUTOR> Fernando Damián Lorenzo García </AUTOR>

        <EMAIL> Fer@yahoo.es </EMAIL>

        <VERSION> 1.0 </VERSION>

        <FECHA> 20.MAYO.99 </FECHA>

    </INFO>

    <PART number="1">
        <Q id="1">

            <QTEXT>¿Por qué tengo que instalar W95?</QTEXT>

            <A> A mi también me parece una buena pregunta.</A>

        </Q>
        <Q id="2">

            <QTEXT>Y de que me vale?</QTEXT>

            <A>Otra ingeniosa pregunta.</A>

        </Q>
    </PART>

</FAQ>
