<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Registro_Ventas[
<!ELEMENT Registro_Ventas(Titulo,Componentes,Conexion_LAN, Servicios,Suma_Total_Productos_Vendidos)>
<!ELEMENT Titulo(#PCDATA)>
<!ELEMENT Componentes(Placas_Base,Procesadores,Discos_Duros,Tarjetas_Graficas, RAMs, Grabadoras_DVD_BluRay, Disqueteras, Multilectores, Tarjetas_Sonido, Torres, Ventilacion, Fuentes_Alimentacion, Cables_Internos,Suma_Total_Componentes_Vendidos)>
<!ELEMENT Placas_Base(Producto*,Suma_Total_Placas_Base)>
<!ELEMENT Procesadores(Producto*,Suma_Total_Procesadores)>
<!ELEMENT Discos_Duros(Producto*,Suma_Total_Discos_Duros)>
<!ELEMENT Tarjetas_Graficas(Producto*,Suma_Total_Tarjetas_Graficas)>
<!ELEMENT RAMs(Producto*,Suma_Total_RAMs)>
<!ELEMENT Grabadoras_DVD_BluRay(Producto*)>
<!ELEMENT Disqueteras(Producto*,Suma_Total_Disqueteras)>
<!ELEMENT Multilectores(Producto*,Suma_Total_Multilectores)>
<!ELEMENT Tarjetas_Sonido(Producto*,Suma_Total_Tarjetas_Sonido)>
<!ELEMENT Torres(Producto*,Suma_Total_Torres)>
<!ELEMENT Ventilacion(Producto*,Suma_Total_Ventilacion)>
<!ELEMENT Fuentes_Alimentacion(Producto*,Suma_Total_Fuentes_Alimentacion)>
<!ELEMENT Cables_Internos(Producto*,Suma_Total_Cables_Internos)>

<!ELEMENT ConexiÃ³n_LAN(Hubs_Switchs, Puntos_Acceso, Routers, Tarjetas_Red, Armarios_Rack, Paneles_Parcheo, Telefonos_VoIP, Cableados_Red,Suma_Total_Conexion_LAN_Vendidos)>
<!ELEMENT Hubs_Switchs(Producto*, Suma_Total_Hubs_Switchs)>
<!ELEMENT Puntos_Acceso(Producto*, Suma_Total_Puntos_Acceso)>
<!ELEMENT Routers(Producto*, Suma_Total_Routers)>
<!ELEMENT Tarjetas_Red(Producto*, Suma_Total_Tarjetas_Red)>
<!ELEMENT Armarios_Rack(Producto*, Suma_Total_Armarios_Rack)>
<!ELEMENT Paneles_Parcheo(Producto*, Suma_Total_Paneles_Parcheo)>
<!ELEMENT Telefonos_VoIP(Producto*, Suma_Total_Telefonos_VoIP)>
<!ELEMENT Cableados_Red(Producto*, Suma_Total_Cableados_Red)>

<!ELEMENT Servicios(Sistemas_Tolerantes_AFallos,Sistemas_Copias_Seguridad,Sistemas_Cifrado_Datos, Suma_Total_Servicios_Vendidos)>
<!ELEMENT Sistemas_Tolerantes_AFallos(Producto*,Suma_Total_Sistemas_Tolerantes_AFallos)>
<!ELEMENT Sistemas_Copias_Seguridad(Producto*,Suma_Total_Sistemas_Copias_Seguridad)>
<!ELEMENT Sistemas_Cifrado_Datos(Producto*,Suma_Total_Sistemas_Cifrado_Datos)>

<!ELEMENT Producto(Modelo*,Codigo*,Precio*,Cantidad_Stock*,Reponer*,Cantidad_Vendidos*)>
<!ELEMENT Modelo(#PCDATA)>
<!ELEMENT Codigo EMPTY>
<!ELEMENT Precio(#PCDATA)>
<!ELEMENT Cantidad_Stock(#PCDATA)>
<!ELEMENT Reponer EMPTY>
<!ELEMENT Cantidad_Vendidos(#PCDATA)>

<!ATTLIST Codigo Producto #REQUIERED>
<!ATTLIST Reponer stock (Si|No)#REQUIERED>
]>




<Registro_Ventas>
    <Titulo>Registro de ventas</Titulo>
    <Componentes>
        <Placas_Base>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

        
        <Suma_Total_Placas_Base></Suma_Total_Placas_Base>
        </Placas_Base>

        <Procesadores>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Procesadores></Suma_Total_Procesadores>
        </Procesadores>

        <Discos_Duros>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Discos_Duros></Suma_Total_Discos_Duros>
        </Discos_Duros>

        <Tarjetas_Graficas>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Tarjetas_Graficas></Suma_Total_Tarjetas_Graficas>
        </Tarjetas_Graficas>

        <RAMs>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_RAMs></Suma_Total_RAMs>
        </RAMs>

        <Grabadoras_DVD_BluRay>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Grabadoras_DVD_BluRay></Suma_Total_Grabadoras_DVD_BluRay>
        </Grabadoras_DVD_BluRay>

        <Disqueteras>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Disqueteras></Suma_Total_Disqueteras>
        </Disqueteras>

        <Multilectores>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Multilectores></Suma_Total_Multilectores>
        </Multilectores>

        <Tarjetas_Sonido>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Tarjetas_Sonido></Suma_Total_Tarjetas_Sonido>
        </Tarjetas_Sonido>

        <Torres>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Torres></Suma_Total_Torres>
        </Torres>

        <Ventilacion>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Ventilacion></Suma_Total_Ventilacion>
        </Ventilacion>

        <Fuentes_Alimentacion>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Fuentes_Alimentacion></Suma_Total_Fuentes_Alimentacion>
        </Fuentes_Alimentacion>

        <Cables_Internos>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Cables_Internos></Suma_Total_Cables_Internos>
        </Cables_Internos>

    <Suma_Total_Componentes_Vendidos></Suma_Total_Componentes_Vendidos>

    </Componentes>

    <Conexion_LAN>

        <Hubs_Switchs>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Hubs_Switchs></Suma_Total_Hubs_Switchs>
        </Hubs_Switchs>

        <Puntos_Acceso>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Puntos_Acceso></Suma_Total_Puntos_Acceso>
        </Puntos_Acceso>

        <Routers>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Routers></Suma_Total_Routers>
        </Routers>

        <Tarjetas_Red>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Tarjetas_Red></Suma_Total_Tarjetas_Red>
        </Tarjetas_Red>

        <Armarios_Rack>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Armarios_Rack></Suma_Total_Armarios_Rack>
        </Armarios_Rack>

        <Paneles_Parcheo>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Paneles_Parcheo></Suma_Total_Paneles_Parcheo>
        </Paneles_Parcheo>

        <Telefonos_VoIP>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Telefonos_VoIP></Suma_Total_Telefonos_VoIP>
        </Telefonos_VoIP>

        <Cableados_Red>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Cableados_Red></Suma_Total_Cableados_Red>
        

        </Cableados_Red>

        <Suma_Total_Conexion_LAN_Vendidos></Suma_Total_Conexion_LAN_Vendidos>

    </Conexion_LAN>

    <Servicios>
        <Sistemas_Tolerantes_AFallos>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Sistemas_Tolerantes_AFallos></Suma_Total_Sistemas_Tolerantes_AFallos>
        </Sistemas_Tolerantes_AFallos>

        <Sistemas_Copias_Seguridad>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Sistemas_Copias_Seguridad></Suma_Total_Sistemas_Copias_Seguridad>
        </Sistemas_Copias_Seguridad>

        <Sistemas_Cifrado_Datos>
            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>

            <Producto>
                <Modelo></Modelo>
                <Codigo producto=""/>
                <Precio></Precio>
                <Cantidad_Stock></Cantidad_Stock>
                <Reponer stock=""/>
                <Cantidad_Vendidos></Cantidad_Vendidos>
            </Producto>
            
        <Suma_Total_Sistemas_Cifrado_Datos></Suma_Total_Sistemas_Cifrado_Datos>
        </Sistemas_Cifrado_Datos>

    <Suma_Total_Servicios_Vendidos></Suma_Total_Servicios_Vendidos>

    </Servicios>

<Suma_Total_Productos_Vendidos></Suma_Total_Productos_Vendidos>

</Registro_Ventas>