=== jonberge1337/alternativa-reto-8/alternativa/alternativaCatalogo.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="tipoPrecio">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[1-9]€" />
			<xsd:pattern value="[1-9][0-9]{1,2}€" />
			<xsd:pattern value="[1-9][0-9]{1,2}\.[0-9]{3}€" />
			<xsd:pattern value="[1-9][0-9]{1,2}\.[0-9]{3}\.[0-9]{3}€" />
			<xsd:pattern value="[1-9],[0-9]{1,2}€" />
			<xsd:pattern value="[1-9][0-9]{1,2},[0-9]{1,2}€" />
			<xsd:pattern value="[1-9]\.[0-9]{3},[0-9]{1,2}€" />
			<xsd:pattern value="[1-9][0-9]{1,2}\.[0-9]{3},[0-9]{1,2}€" />
			<xsd:pattern value="[1-9][0-9]{1,2}\.[0-9]{3}\.[0-9]{3},[0-9]{1,2}€" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipoCodigo">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[1-9][0-9]{1,8}" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipoVacio">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="0" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipoProducto">
		<xsd:restriction base="xsd:string">
			<xsd:pattern
				value="(Placa base|Procesador|Disco duro|Tarjeta grafica|Memoria RAM|Disquetera|Multilector|Tarjeta sonido|Torre|Ventilador|Fuente alimentacion|Cables internos|hub/switch|Puntos de acceso|Router|Tarjeta red|Armario rack|Telefonos VoIP|Cable|Paneles parcheo|Sistemas Tolerantes a Fallos|Sistemas Copias Seguridad|Sistemas Cifrado Datos)" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="soloLetras">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z áéíóúÁÉÍÓÚ]" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipoBooleana">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(Si|SI|si|No|NO|no)" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipoImagen">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z1-9]\.(jpg|png)" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="catalogo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="componente" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="descripcion" type="xsd:string" />
							<xsd:element name="caracteristicas">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="caracteristica">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:string">
														<xsd:attribute name="tipo" type="soloLetras" />
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="tipo" use="required" type="tipoProducto" />
									<xsd:attribute name="marca" use="required" type="xsd:string" />
									<xsd:attribute name="modelo" type="xsd:string" />
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="codigo">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="tipoVacio">
											<xsd:attribute name="producto" type="tipoCodigo" />
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="precio" type="tipoPrecio" />
							<xsd:element name="disponibilidad">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="tipoVacio">
											<xsd:attribute name="stock" type="tipoBooleana" />
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="foto">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="tipoVacio">
											<xsd:attribute name="src" type="tipoImagen" />
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="servicio" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="modelo" type="xsd:string" />
							<xsd:element name="descripcion" type="xsd:string" />
							<xsd:element name="codigo">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="tipoVacio">
											<xsd:attribute name="producto" type="tipoCodigo" />
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="precio" type="tipoPrecio" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== jonberge1337/alternativa-reto-8/alternativa/alternativaCatalogo.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alternativaCatalogo.xsd">
    <componente tipo="Placa base" marca="Gygabyte" modelo="B450M DS3H">
        <descripcion>Las placas base GIGABYTE serie 400 maximizan el potencial de su PC con la tecnología AMD StoreMI.
            StoreMI acelera los dispositivos de almacenamiento tradicionales para reducir los tiempos de arranque y
            mejorar la experiencia general del usuario. Esta utilidad fácil de usar combina la velocidad de las SSD con
            la alta capacidad de las unidades de disco duro en una sola unidad, mejora las velocidades de lectura /
            escritura del dispositivo para que coincida con las SSD, aumenta el rendimiento de los datos a un valor
            increíble y transforma las PC de uso cotidiano a un sistema impulsado por el rendimiento. Además, cuenta con
            Smart Fan 5, con esta refrigeración los usuarios pueden asegurarse de que su PC gaming puede mantener un
            rendimiento estable mientras se mantiene refrigerado. Smart Fan 5 permite a los usuarios intercambiar sus
            conectores para los ventiladores para reflejar diferentes sensores térmicos en diferentes ubicaciones de la
            placa base. Además con Smart Fan 5 los conectores híbridos para el ventilador soportan ventiladores PWM y de
            voltaje, esto hace que la placa base este más adaptada a montar refrigeración líquida.</descripcion>
        <caracteristicas>
            <caracteristica tipo="Chipset">intel H110</caracteristica>
            <caracteristica tipo="Conectividad">Bluetooth</caracteristica>
            <caracteristica tipo="Conectividad">Wifi</caracteristica>
            <caracteristica tipo="Conectividad">cable</caracteristica>
            <caracteristica tipo="Conexion">DVI</caracteristica>
            <caracteristica tipo="Conexion">HDMI</caracteristica>
            <caracteristica tipo="Conexion">Jack</caracteristica>
            <caracteristica tipo="Conexion interna">Sata 3</caracteristica>
            <caracteristica tipo="Factor forma">Micro ATX</caracteristica>
            <caracteristica tipo="Tecnologia Multi-GPU">NVIDIA SLI</caracteristica>
            <caracteristica tipo="Tipo socket">Cpu integrada</caracteristica>
        </caracteristicas>
        <codigo producto="4567" />
        <precio>108,99€</precio>
        <disponibilidad stock="Si" />
        <foto src="imagen1.jpg" />
    </componente>

    <componente tipo="Placa base" marca="Asus" modelo="Prime A320M-K">
        <descripcion>ASUS Prime es la próxima evolución de la placa madre ASUS,nacida de un pedigrí que se remonta a
            1989. Nuestro equipo de ingenieros de clase mundial son apasionados de empoderar a todos para disfrutar de
            los beneficios de la personalización y afinación y la fuerza motriz detrás del desarrollo dePrime es hacer
            que los controles avanzados de los entusiastas sean fácilmente accesibles, maximizando el rendimiento, la
            estabilidad y la compatibilidad para las mejores experiencias de la PC DIY.En pocas palabras: es hora de
            Prime.</descripcion>
        <caracteristicas>
            <caracteristica tipo="Chipset">intel H110</caracteristica>
            <caracteristica tipo="Conectividad">cable</caracteristica>
            <caracteristica tipo="Conexion">DVI</caracteristica>
            <caracteristica tipo="Conexion">Jack</caracteristica>
            <caracteristica tipo="Conexion interna">Sata 3</caracteristica>
            <caracteristica tipo="Factor forma">Micro ATX</caracteristica>
            <caracteristica tipo="Tecnologia Multi-GPU">NVIDIA SLI</caracteristica>
            <caracteristica tipo="Tipo socket">Cpu integrada</caracteristica>
        </caracteristicas>
        <codigo producto="2321" />
        <precio>65,25€</precio>
        <disponibilidad stock="Si" />
        <foto src="imagen1.jpg" />
    </componente>

    <componente tipo="Procesador" marca="AMD" modelo="Ryzen 5 2600 3.4 Ghz">
        <descripcion>Te presentamos el AMD Ryzen 5 2600, un procesador que cuenta con 6 núcleos, socket AMD AM4 y
            arquitectura de 64 bits. Y es que la forma de contratacar de AMD ha sido contundente, lo nuevos Ryzen no
            solo demuestran mayor efectividad si no tambien un consumo mucho más contenido que sus predecesores. Los
            procesadores AMD Ryzen están diseñados para satisfacer las necesidades de los usuarios más avanzados y
            exigentes. Para minimizar la latencia de respuesta AMD lanza la tecnología Turbo Core que dará la mayor
            frecuencia del núcleo cuando lo necesita.</descripcion>
        <caracteristicas>
            <caracteristica tipo="Procesador">Familia de procesador: AMD Ryzen 5</caracteristica>
            <caracteristica tipo="Procesador">Frecuencia del procesador: 3,4 GHz</caracteristica>
            <caracteristica tipo="Procesador">Número de núcleos de procesador: 6</caracteristica>
            <caracteristica tipo="Procesador">Socket de procesador: Zócalo AM4</caracteristica>
            <caracteristica tipo="Procesador">Litografía del procesador: 12 nm</caracteristica>
            <caracteristica tipo="Procesador">modelo del procesador: 2600</caracteristica>
            <caracteristica tipo="Procesador">Número de filamentos de procesador: 12</caracteristica>
            <caracteristica tipo="Procesador">Modo de procesador operativo: 32-bit, 64 bits</caracteristica>
            <caracteristica tipo="Procesador">Caché del procesador: 16 MB</caracteristica>
            <caracteristica tipo="Procesador">Tipo de cache en procesador: L3</caracteristica>
            <caracteristica tipo="Procesador">Frecuencia del procesador turbo: 3,9 GHz</caracteristica>
            <caracteristica tipo="Memoria">Canales de memoria que admite el procesador: Dual</caracteristica>
            <caracteristica tipo="Memoria">Tipos de memoria que admite el procesador: DDR4-SDRAM</caracteristica>
            <caracteristica tipo="Memoria">Velocidad de reloj de memoria que admite el procesador: 2933 MHz
            </caracteristica>
            <caracteristica tipo="Control de energia">Potencia de diseño térmico (TDP): 65 W</caracteristica>
            <caracteristica tipo="Graficos">Adaptador gráfico incorporado: No</caracteristica>
            <caracteristica tipo="Graficos">Adaptador de gráficos discreto: No</caracteristica>
            <caracteristica tipo="Graficos">modelo de adaptador gráfico incorporado: No disponible</caracteristica>
            <caracteristica tipo="Graficos">modelo de adaptador de gráficos discretos: No disponible</caracteristica>
            <caracteristica tipo="Caracteristicas">Versión de entradas de PCI Express: 3.0</caracteristica>
            <caracteristica tipo="Caracteristicas">Configuraciones PCI Express: 1x16</caracteristica>
        </caracteristicas>
        <codigo producto="157402" />
        <precio>165,99€</precio>
        <disponibilidad stock="Si" />
        <foto src="imagen1.jpg" />
    </componente>

    <componente tipo="Procesador" marca="intel" modelo="Core i5-8400 2.8GHz BOX">
        <descripcion>Te presentamos el Intel Core i5-8400, un procesador de 8ª Generación y socket Intel 1151.
        </descripcion>
        <caracteristicas>
            <caracteristica tipo="General">Type CPU / Microprocessor Market segment Desktop</caracteristica>
            <caracteristica tipo="General">Family Intel Core i5</caracteristica>
            <caracteristica tipo="General">Model number ? i5-8400</caracteristica>
            <caracteristica tipo="General">Frequency ? 2800 MHz</caracteristica>
            <caracteristica tipo="General">Turbo frequency 4000 MHz (1 core)</caracteristica>
            <caracteristica tipo="General">3900 MHz (2, 3 or 4 cores)</caracteristica>
            <caracteristica tipo="General">3800 MHz (5 or 6 cores)</caracteristica>
            <caracteristica tipo="General">Low power frequency 800 MHz</caracteristica>
            <caracteristica tipo="General">Bus speed ? 8 GT/s DMI</caracteristica>
            <caracteristica tipo="General">Clock multiplier ? 28</caracteristica>
            <caracteristica tipo="General">Package 1151-land Flip-Chip Land Grid Array</caracteristica>
            <caracteristica tipo="General">Socket Socket 1151 / H4 / LGA1151</caracteristica>
            <caracteristica tipo="General">Size 1.48" x 1.48" / 3.75cm x 3.75cm</caracteristica>
            <caracteristica tipo="Arquitectura">Microarchitecture Coffee Lake</caracteristica>
            <caracteristica tipo="Arquitectura">Processor core ? Coffee Lake-S</caracteristica>
            <caracteristica tipo="Arquitectura">Manufacturing process 0.014 micron</caracteristica>
            <caracteristica tipo="Arquitectura">Data width 64 bit</caracteristica>
            <caracteristica tipo="Arquitectura">The number of CPU cores 6</caracteristica>
            <caracteristica tipo="Arquitectura">The number of threads 6</caracteristica>
            <caracteristica tipo="Arquitectura">Floating Point Unit Integrated</caracteristica>
            <caracteristica tipo="Arquitectura">Level 1 cache size ? 6 x 32 KB data caches</caracteristica>
            <caracteristica tipo="Arquitectura">Level 2 cache size ? 6 x 256 KB caches</caracteristica>
            <caracteristica tipo="Arquitectura">Level 3 cache size 9 MB shared cache</caracteristica>
            <caracteristica tipo="Arquitectura">Physical memory 64 GB</caracteristica>
        </caracteristicas>
        <codigo producto="139906" />
        <precio>204,90€</precio>
        <disponibilidad stock="Si" />
        <foto src="imagen1.jpg" />
    </componente>

    <componente tipo="Disco duro" marca="Seagate" modelo="BarraCuda">
        <descripcion>Versátiles. Rápidos. Fiables. La unidad de disco duro más increíble que haya conocido.
